openapi: 3.0.4
info:
  title: Units log models
  description: Log models for the measurement units service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Common log model
      description: A unit log model that is common for all the marketplace microservices
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        unit:
          $ref: '#/components/schemas/UnitLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    UnitLogModel:
      title: Unit log model
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - suggest
        requestUnit:
          $ref: '#/components/schemas/UnitLog'
        requestFilter:
          $ref: '#/components/schemas/UnitFilterLog'
        responseUnit:
          $ref: '#/components/schemas/UnitLog'
        responseUnits:
          type: array
          items:
            $ref: '#/components/schemas/UnitLog'

    ErrorLogModel:
      title: Error log model
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    UnitLog:
      title: Unit log model
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        alias:
          type: string
        status:
          type: string
        systemUnitId:
          type: string

    UnitFilterLog:
      title: Filter log model
      properties:
        searchString:
          type: string
