ktor:
  development: true
  deployment:
    port: "$PORT:8080"
  watch:
    - classes
    - resources
  application:
    modules:
      - com.crowdproj.marketplace.units.app.ApplicationKt.module
  urls:
    - "http://0.0.0.0:8080/"
    - "http://127.0.0.1:8080/"
    - "http://192.168.0.182:8080/"
